# Use require with path relative to /lib
$LOAD_PATH.unshift('./lib').uniq!

require 'bikesurf/database/dummy_data'
require 'rubocop/rake_task'

RuboCop::RakeTask.new(:rubocop)

namespace :database do
  task :migrate do
    DataMapper.auto_migrate!
    DataMapper.auto_upgrade!
    puts 'Recreating database'
  end

  task :fill_dummy do
    DataMapper.auto_migrate!
    DataMapper.auto_upgrade!

    puts 'Database dropped and created'

    Bikesurf::Database::DummyData.new.fill_dummy_data

    puts 'Database filled'
  end
end

task :serve do
  `guard -i`
end

namespace :server do
  task :start do
    exec('rackup -p 1234 -P /tmp/bikesurf_server.pid -s thin') if fork.nil?
  end

  task :stop do

    `kill $(cat /tmp/bikesurf_server.pid)` if File.exists?('/tmp/bikesurf_server.pid')
    sleep 1
  end

  task restart: [:stop, :start]
end

task :css => ['public/css/styles.css']

rule '.css' => '.scss' do |t|
    p t
  `sass #{t.source} #{t.name}`
end

task default: [:rubocop]
task start: [:css]
