# Use require with path relative to /lib
$:.unshift("./lib").uniq!

require 'bikesurf/database/models'

namespace :database do
	task :migrate do
		DataMapper.auto_migrate!
		DataMapper.auto_upgrade!
		puts "creating database"
	end
end