# Use require with path relative to /lib
$LOAD_PATH.unshift('./lib').uniq!

require 'bikesurf/database/dummy_data'
require 'rubocop/rake_task'
require 'rakeup'

RuboCop::RakeTask.new(:rubocop)

namespace :database do
  task :migrate do
    DataMapper.auto_migrate!
    DataMapper.auto_upgrade!
    puts 'Recreating database'
  end

  task :fill_dummy do
    DataMapper.auto_migrate!
    DataMapper.auto_upgrade!

    puts 'Database dropped and created'

    Bikesurf::Database::DummyData.new.fill_dummy_data

    puts 'Database filled'
  end
end

task :serve do
  `rackup -p 1234 -s thin`
end

RakeUp::ServerTask.new do |t|
  t.port = 1234
  t.pid_file = '/tmp/bikesurf_server.pid'   # fixme: support windoze
  t.rackup_file = 'config.ru'
  t.server = :thin
end

task :css => ['public/css/styles.css']

rule '.css' => '.scss' do |t|
    p t
  `sass #{t.source} #{t.name}`
end

task default: [:rubocop, :css]
task serve: [:css]
